title: Stupid compiler tricks
email: dberlin@dberlin.org
baseurl: ""
theme: jekyll-theme-midnight
highlighter: pygments
markdown: kramdown
github_username: dberlin
url: "http://blog.stupidcompilertricks.com"

